#!/bin/bash
VARS="/usr/local/emhttp/state/var.ini"
source $VARS

if [ "$shareSMBEnabled" == "ads" ]; then
	/usr/local/emhttp/plugins/active.directory/scripts/rc.active.directory apply
else
	rm -f /etc/samba/smb-active.directory.conf
fi
