#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

VARS="${DOCROOT}/state/var.ini"
source $VARS

if [ "$shareSMBEnabled" == "ads" ]; then
	${DOCROOT}/plugins/active.directory/scripts/rc.shutdown  > /dev/null 2>&1
	${DOCROOT}/plugins/active.directory/scripts/rc.cleanup > /dev/null 2>&1
fi
